# Generated by Django 3.1.4 on 2021-02-02 09:04

from django.db import migrations, models
import django.db.models.deletion
import djangocms_text_ckeditor.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cms', '0022_auto_20180620_1551'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeaserTextExtension',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teaser_text', djangocms_text_ckeditor.fields.HTMLField(blank=True)),
                ('extended_object', models.OneToOneField(editable=False, on_delete=django.db.models.deletion.CASCADE, to='cms.title')),
                ('public_extension', models.OneToOneField(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='draft_extension', to='page_extensions.teasertextextension')),
            ],
            options={
                'verbose_name': 'Teaser Text',
            },
        ),
        migrations.CreateModel(
            name='TeaserImageExtension',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teaser_image', models.ImageField(default='default_teaser_image.jpeg', upload_to='teaser_images/')),
                ('extended_object', models.OneToOneField(editable=False, on_delete=django.db.models.deletion.CASCADE, to='cms.page')),
                ('public_extension', models.OneToOneField(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='draft_extension', to='page_extensions.teaserimageextension')),
            ],
            options={
                'verbose_name': 'Teaser Image',
            },
        ),
        migrations.CreateModel(
            name='EventDataExtension',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_from', models.DateTimeField(blank=True, help_text='Starting date of the event. (has to be set in order for event to show in the calendar)', null=True, verbose_name='FROM')),
                ('date_to', models.DateField(blank=True, help_text='Finishing date for recurring events. (the date is inclusive, so, in case of one day events, it should be equal to the starting date of the event or left blank)', null=True, verbose_name='TO')),
                ('extended_object', models.OneToOneField(editable=False, on_delete=django.db.models.deletion.CASCADE, to='cms.page')),
                ('festival', models.ForeignKey(blank=True, help_text='If the event is part of a festival, select one. Otherwise, leave unset. (the information is used to generate festival programs and parts of calendar)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='parent_festival', to='cms.page')),
                ('public_extension', models.OneToOneField(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='draft_extension', to='page_extensions.eventdataextension')),
            ],
            options={
                'verbose_name': 'Event Scheduling',
            },
        ),
    ]
