# Generated by Django 3.1.4 on 2021-03-24 09:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0022_auto_20180620_1551'),
        ('page_extensions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeaturedExtension',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('featured', models.BooleanField(default=False)),
                ('extended_object', models.OneToOneField(editable=False, on_delete=django.db.models.deletion.CASCADE, to='cms.page')),
                ('public_extension', models.OneToOneField(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='draft_extension', to='page_extensions.featuredextension')),
            ],
            options={
                'verbose_name': 'Featured',
            },
        ),
    ]
