# Generated by Django 3.2.3 on 2023-03-15 12:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0022_auto_20180620_1551'),
        ('page_extensions', '0005_imageextension'),
    ]

    operations = [
        migrations.CreateModel(
            name='FestivalYearExtension',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('festival_year', models.DecimalField(decimal_places=0, default=2023, max_digits=4)),
                ('extended_object', models.OneToOneField(editable=False, on_delete=django.db.models.deletion.CASCADE, to='cms.page')),
                ('public_extension', models.OneToOneField(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='draft_extension', to='page_extensions.festivalyearextension')),
            ],
            options={
                'verbose_name': 'Festival year',
            },
        ),
    ]
